export const countriesDialCode = [
  { name: "Afghanistan", code: "AF", flag: "🇦🇫", dialCode: "+93" },
  { name: "Albania", code: "AL", flag: "🇦🇱", dialCode: "+355" },
  { name: "Algeria", code: "DZ", flag: "🇩🇿", dialCode: "+213" },
  { name: "Andorra", code: "AD", flag: "🇦🇩", dialCode: "+376" },
  { name: "Angola", code: "AO", flag: "🇦🇴", dialCode: "+244" },
  { name: "Antigua and Barbuda", code: "AG", flag: "🇦🇬", dialCode: "+1-268" },
  { name: "Argentina", code: "AR", flag: "🇦🇷", dialCode: "+54" },
  { name: "Armenia", code: "AM", flag: "🇦🇲", dialCode: "+374" },
  { name: "Australia", code: "AU", flag: "🇦🇺", dialCode: "+61" },
  { name: "Austria", code: "AT", flag: "🇦🇹", dialCode: "+43" },
  { name: "Azerbaijan", code: "AZ", flag: "🇦🇿", dialCode: "+994" },
  { name: "Bahamas", code: "BS", flag: "🇧🇸", dialCode: "+1-242" },
  { name: "Bahrain", code: "BH", flag: "🇧🇭", dialCode: "+973" },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩", dialCode: "+880" },
  { name: "Barbados", code: "BB", flag: "🇧🇧", dialCode: "+1-246" },
  { name: "Belarus", code: "BY", flag: "🇧🇾", dialCode: "+375" },
  { name: "Belgium", code: "BE", flag: "🇧🇪", dialCode: "+32" },
  { name: "Belize", code: "BZ", flag: "🇧🇿", dialCode: "+501" },
  { name: "Benin", code: "BJ", flag: "🇧🇯", dialCode: "+229" },
  { name: "Bhutan", code: "BT", flag: "🇧🇹", dialCode: "+975" },
  { name: "Bolivia", code: "BO", flag: "🇧🇴", dialCode: "+591" },
  { name: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦", dialCode: "+387" },
  { name: "Botswana", code: "BW", flag: "🇧🇼", dialCode: "+267" },
  { name: "Brazil", code: "BR", flag: "🇧🇷", dialCode: "+55" },
  { name: "Brunei", code: "BN", flag: "🇧🇳", dialCode: "+673" },
  { name: "Bulgaria", code: "BG", flag: "🇧🇬", dialCode: "+359" },
  { name: "Burkina Faso", code: "BF", flag: "🇧🇫", dialCode: "+226" },
  { name: "Burundi", code: "BI", flag: "🇧🇮", dialCode: "+257" },
  { name: "Cambodia", code: "KH", flag: "🇰🇭", dialCode: "+855" },
  { name: "Cameroon", code: "CM", flag: "🇨🇲", dialCode: "+237" },
  { name: "Canada", code: "CA", flag: "🇨🇦", dialCode: "+1" },
  { name: "Cape Verde", code: "CV", flag: "🇨🇻", dialCode: "+238" },
  { name: "Chad", code: "TD", flag: "🇹🇩", dialCode: "+235" },
  { name: "Chile", code: "CL", flag: "🇨🇱", dialCode: "+56" },
  { name: "China", code: "CN", flag: "🇨🇳", dialCode: "+86" },
  { name: "Colombia", code: "CO", flag: "🇨🇴", dialCode: "+57" },
  { name: "Congo (Kinshasa)", code: "CD", flag: "🇨🇩", dialCode: "+243" },
  { name: "Costa Rica", code: "CR", flag: "🇨🇷", dialCode: "+506" },
  { name: "Croatia", code: "HR", flag: "🇭🇷", dialCode: "+385" },
  { name: "Cuba", code: "CU", flag: "🇨🇺", dialCode: "+53" },
  { name: "Cyprus", code: "CY", flag: "🇨🇾", dialCode: "+357" },
  { name: "Czech Republic", code: "CZ", flag: "🇨🇿", dialCode: "+420" },
  { name: "Denmark", code: "DK", flag: "🇩🇰", dialCode: "+45" },
  { name: "Dominican Republic", code: "DO", flag: "🇩🇴", dialCode: "+1-809" },
  { name: "Ecuador", code: "EC", flag: "🇪🇨", dialCode: "+593" },
  { name: "Egypt", code: "EG", flag: "🇪🇬", dialCode: "+20" },
  { name: "France", code: "FR", flag: "🇫🇷", dialCode: "+33" },
  { name: "Germany", code: "DE", flag: "🇩🇪", dialCode: "+49" },
  { name: "Ghana", code: "GH", flag: "🇬🇭", dialCode: "+233" },
  { name: "Greece", code: "GR", flag: "🇬🇷", dialCode: "+30" },
  { name: "Nigeria", code: "NG", flag: "🇳🇬", dialCode: "+234" },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧", dialCode: "+44" },
  { name: "United States", code: "US", flag: "🇺🇸", dialCode: "+1" },
];
