export const userSelectionSteps = ["1", "2", "3"];
export const sportyTypes = [
  "Football",
  "Basketball",
  "Volleyball",
  "Tennis",
  "Badminton",
  "Cricket",
  "Hockey",
  "Rugby",
  "Baseball",
  "Table Tennis",
  "Swimming",
  "Athletics",
  "Cycling",
  "Gymnastics",
  "Martial Arts",
  "Boxing",
  "Golf",
  "Skiing",
  "Surfing",
  "Rowing",
  "Ice Hockey",
];
