export enum authScreenNames {
  USER_SELECTION = "UserSelection",
  AGE_SELECTION = "AgeSelection",
  LOGIN = "Login",
  SIGN_UP = "SignUp",
  MEMBERSHIP = "Membership",
  EVENTS = "Events",
  ANOTHER_EVENTS = "AnotherEvents",
  INSIGHTS = "Insights",
  ANOTHER_MEMBERSHIP = "AnotherMembership",
  PREDICTION_SERVICES = "PredictionServices",
  DAILY_COUPON = "DailyCoupon",
  DAILY_SINGLE_MATCHES = "DailySingleMatches",
  UPGRADE_MEMBERSHIP = "UpgradeMembership",
}

export enum bottomTabScreenNames {
  FOOTBALL_STACK = "FootballStack",
  FOR_YOU_STACK = "ForYouStack",
  FAVORITES_STACK = "FavoritesStack",
}

export enum appScreenNames {
  BOTTOM_TAB_STACK = "BottomTabStack",
  FOOTBALL = "Football",
  FOR_YOU = "ForYou",
  FAVORITES = "Favorites",
  FIXTURE_INFO = "FixtureInfo",
  MATCH_HIGHLIGHTS = "MatchHighlights",
  MORE = "More",
  NOTIFICATIONS = "Notifications",
  SETTINGS = "Settings",
  LANGUAGE = "Language",
  DEFAULT_SPORT = "DefaultSport",
  FOR_YOU_NEWS = "ForYouNews",
  ONE_MATCH = "OneMatch",
  TEAM = "Team",
  ANOTHER_TEAM = "AnotherTeam",
  ANOTHER_PLAYER_TEAM = "AnotherPlayerTeam",
  BASKETBALL_FIXTURE_INFO = "BasketballFixtureInfo",
  TENNIS_FIXTURE_INFO = "TennisFixtureInfo",
  AMERICAN_FOOTBALL_FIXTURE_INFO = "AmericanFootballFixtureInfo",
  CRICKET_FIXTURE_INFO = "CricketFixtureInfo",
  ICE_HOCKEY_FIXTURE_INFO = "IceHockeyFixtureInfo",
}
