import {
  FOOTBALL_FIXTURES,
  FOOTBALL_LEAGUES,
  FOOTBALL_MARKET,
  FOOTBALL_MATCHES,
} from "@env";

export const endpoint = {
  AUTH: {},
  APP: {
    GET_FOOTBALL_MARKET: FOOTBALL_MARKET,
    GET_FOOTBALL_FIXTURES: FOOTBALL_FIXTURES,
    GET_FOOTBALL_MATCHES: FOOTBALL_MATCHES,
    GET_FOOTBALL_LEAGUES: FOOTBALL_LEAGUES,
  },
};
